### PR TITLE
V0.0.5

### PR DESCRIPTION
**Pull request by kwilcox**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kwilcox** [comment]
My god I didn't update the SHA, is it Friday?

**Comment by ocefpaf** [comment]
> My god I didn't update the SHA, is it Friday?

And I did not catch it :smile: 

(In my defense I've been travelling for ~24 hours now, "sleeping" only on planes.)

**Comment by kwilcox** [comment]
I'm spoiled by the bot, haven't done this in awhile...

**Comment by ocefpaf** [comment]
> I'm spoiled by the bot, haven't done this in awhile...

Yeah. The bot should've catch this one.

**Pull request merged**
